/* eslint-disable operator-linebreak */

// auth actionTypes
export const AUTH_START = 'AUTH_START'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
// auth modal actionTypes
export const SHOW_SIGN_IN = 'SHOW_SIGN_IN'
export const SHOW_SIGN_UP = 'SHOW_SIGN_UP'
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL'

// products actionTypes
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCT_FAIL'
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCT'

// orders actionTypes
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
export const CLEAR_ORDERS = 'CLEAR_ORDERS'

// filter actionTypes
export const FILTER_NAME = 'FILTER_NAME'
export const FILTER_PRICE = 'FILTER_PRICE'
export const FILTER_BRAND = 'FILTER_BRAND'
export const FILTER_SIZE = 'FILTER_SIZE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const SORT_ITEMS = 'SORT_ITEMS'

// cart actionTypes
export const GET_CART_LOCAL_STORAGE = 'GET_CART_LOCAL_STORAGE'
export const ADD_ITEM_IN_CART = 'ADD_ITEM_IN_CART'
export const REMOVE_ITEM_IN_CART = 'REMOVE_ITEM_IN_CART'
export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART'
export const ADD_WISHLIST_TO_CART = 'ADD_WISHLIST_TO_CART'
export const ADD_ALL_WISHLIST_TO_CART = 'ADD_ALL_WISHLIST_TO_CART'
export const CHANGE_CART_ITEM_QUANTITY = 'CHANGE_CART_ITEM_QUANTITY'
export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS'

// wishlist actionTypes
export const FETCH_WISHLIST_START = 'FETCH_WISHLIST_START'
export const FETCH_WISHLIST_ITEMS_SUCCESS = 'FETCH_WISHLIST_ITEMS_SUCCESS'
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST'
export const ADD_SIZE_IN_WISHLIST_ITEM = 'ADD_SIZE_IN_WISHLIST_ITEM'
export const REMOVE_WISHLIST_TO_BE_ADDED_IN_CART =
  'REMOVE_WISHLIST_TO_BE_ADDED_IN_CART'
export const ADD_ITEM_IN_WISHLIST_SUCCESS = 'ADD_ITEM_IN_WISHLIST_SUCCESS'
export const REMOVE_ITEM_IN_WISHLIST_SUCCESS = 'REMOVE_ITEM_TO_WISHLIST_SUCCESS'

// reviews actionTypes
export const FETCH_REVIEWS_START = 'FETCH_REVIEWS_START'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS'
